### ISSUE TITLE
ESDS.H is named wrongly

### ISSUE THREAD

**Issue by kasperholtze** [kaltura/Android-HLS-lib#48]
jni/ESDS.H should be named ESDS.h - will not compile on Linux otherwise.

**Comment by KalturaCommunity** [comment]
Hello and thank you for reporting.
Can you please submit a pull request so the credit for the find and fix goes to you?


May the source be with you,

Jess Portnoy



-------- Original message --------

**Comment by kasperholtze** [comment]
Will try - haven't tried it before, but I am happy to try!

**Comment by KalturaCommunity** [comment]
Please do:)
It may be a small fix but.. nonetheless, we prefer to give proper credits for our contributors.

Plus, hoping for additional ones from you in the future.


May the source be with you,

Jess Portnoy



-------- Original message --------

**Comment by kasperholtze** [comment]
Success?
#51

**Comment by jessp01** [comment]
Hi @kasperholtze,

Just wanted to let you know we now have Travis CI integration in place to prevent such things from happening again:)
https://travis-ci.org/jessp01/Android-HLS-lib

Thanks for the report and pull,

**Comment by kasperholtze** [comment]
Great, thank you :)
