### ISSUE TITLE
Off by one (or two)

### ISSUE THREAD

**Issue by kasperholtze** [kaltura/Android-HLS-lib#49]
MainfestPlaylist.java line 26:
int endIndex = firstCommaIndex > -1 ? firstCommaIndex : input.length() + 1;

Guess this should be 
int endIndex = firstCommaIndex > -1 ? firstCommaIndex : input.length() - 1;

The application crashes with an out-of-bounds exception otherwise.

**Comment by kasperholtze** [comment]
#52

**Comment by jessp01** [comment]
Closing since we have a pull request on this one.
Thanks again @kasperholtze
